---
cog_bundle_version: 4
name: "erlang-echo"
description: "Echo from Erlang"
version: "0.1.0"
docker:
  image: "cogcmd/erlang-echo"
  tag: "0.1.0"
commands:
  erlang-echo:
    executable: "/root/echo.sh"
    rules:
      - "allow"
